bash ./install_libvmaf.sh && \
bash ./install_opencore-amr.sh && \
bash ./install_libx264.sh && \
bash ./install_libx265.sh && \
bash ./install_libogg.sh && \
bash ./install_libopus.sh && \
bash ./install_libvorbis.sh && \
bash ./install_libtheora.sh && \
bash ./install_libvpx.sh && \
bash ./install_libwebp.sh && \
bash ./install_libmp3lame.sh && \
bash ./install_xvid.sh && \
bash ./install_fdk-aac.sh && \
bash ./install_openjpeg.sh && \
bash ./install_freetype.sh && \
bash ./install_vidstab.sh && \
bash ./install_fribidi.sh && \
bash ./install_fontconfig.sh && \
bash ./install_libass.sh && \
bash ./install_kvazaar.sh && \
bash ./install_aom.sh && \
bash ./install_libxcb.sh && \
bash ./install_xproto.sh && \
bash ./install_libXau.sh && \
bash ./install_libpthread-stubs.sh && \
bash ./install_libxcb-proto.sh && \
bash ./install_libxcb.sh && \
bash ./install_libxml2.sh && \
bash ./install_libbluray.sh && \
bash ./install_libzmq.sh && \
bash ./install_srt.sh && \
bash ./install_libpng.sh && \
bash ./install_b24.sh && \
bash ./install_ffmpeg.sh
